language: node_js
node_js:
  - 'stable'
  - 'lts/*'
before_script:
  - 'npm install grunt-cli -g'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'sleep 3'

script: npm run lint && npm run test && grunt pre-build && npm run test:e2e
