language: node_js
os:
  - linux
  - osx
node_js:
  - 'stable'
  - 'lts/*'
script:
  - 'npm run lint'
  - 'npm run test'
  - 'if [[ ${TRAVIS_BRAHCN} = "master" && ${TRAVIS_NODE_VERSION} = "stable" ]]; then ./script/e2e-runner.sh; fi'
